version: '3.8'
services:
  pg-db:
    image: postgres:14.5-alpine
    container_name: postgres_anime_container
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${PG_MAPPING_PORT}:5432'

volumes:
  postgres: